# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-24 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20181124_1850'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVotedByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=b'0'),
        ),
        migrations.AddField(
            model_name='question',
            name='answerers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='due_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='due_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='editing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='min_answerers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_picture',
            field=models.ImageField(max_length=600, null=True, upload_to=questions.models.content_file_name),
        ),
        migrations.AddField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(allow_unicode=True, default='null', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_html',
            field=models.TextField(editable=False, max_length=600),
        ),
        migrations.AddField(
            model_name='questionvotedbyuser',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_question_by_user', to='questions.Answer'),
        ),
        migrations.AddField(
            model_name='questionvotedbyuser',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answered_by_user', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionvotedbyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_voted_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerbyuser',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered', to='questions.Answer'),
        ),
        migrations.AddField(
            model_name='answerbyuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='answerbyuser',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answered', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='answerbyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionvotedbyuser',
            unique_together=set([('question', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='answerbyuser',
            unique_together=set([('question', 'user', 'group')]),
        ),
    ]
