# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-19 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20181124_1850'),
        ('questions', '0002_auto_20190119_2023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerbyuser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='answerbyuser',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerbyuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='answerbyuser',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answerbyuser',
            name='user',
        ),
        migrations.AddField(
            model_name='questionvotedbyuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='questionvotedbyuser',
            unique_together=set([('question', 'user', 'group')]),
        ),
        migrations.DeleteModel(
            name='AnswerByUser',
        ),
    ]
