# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181124_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_picture',
            field=models.FileField(max_length=600, null=True, upload_to=questions.models.content_file_name),
        ),
    ]
