# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-24 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181204_2026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'answer')]),
        ),
    ]
