# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190107_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
