# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-07 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
